ActiveAdmin.register Visitor do
  # On create, card_number/line_user_id are never client-assignable: the
  # card number is auto-generated by the system, and line_user_id stays
  # blank until the visitor links a LINE account themselves.
  permit_params do
    if params[:action] == "create"
      [ :display_name, :avatar_url ]
    else
      [ :display_name, :avatar_url, :line_user_id, :card_number ]
    end
  end

  filter :display_name_cont, label: "表示名"
  filter :card_number_cont, label: "カード番号"
  filter :line_user_id_cont, label: "LINE ID"
  filter :created_at

  index do
    selectable_column
    id_column
    column :display_name
    column :card_number
    column :line_user_id
    column("スタンプ数") { |visitor| visitor.stamps.size }
    column("ランク") { |visitor| visitor.rank&.name }
    column :created_at
    actions
  end

  show do
    if resource.card_number.present?
      panel "会員カード番号" do
        div class: "card-number-display" do
          span resource.card_number
        end
        para "紙の会員カードにこの番号を記入してください。", style: "text-align: center; color: #666;"
      end
    end

    attributes_table do
      row :id
      row :display_name
      row :card_number
      row :line_user_id
      row :avatar_url
      row("ランク") { resource.rank&.name || "-" }
      row("スタンプ数") { resource.stamps.size }
      row :created_at
      row :updated_at
    end

    panel "スタンプを手動付与" do
      para "紙カード来場者への正規フォールバック、またはNFCタグ故障時の緊急オーバーライド用です。"
      render partial: "grant_stamp_form", locals: { visitor: resource, events: Event.order(held_on: :desc) }
    end

    panel "来場履歴" do
      table_for resource.stamps.includes(:event, :granted_by).order(checked_in_at: :desc) do
        column("イベント") { |stamp| stamp.event.title }
        column("開催日") { |stamp| stamp.event.held_on }
        column("チェックイン日時") { |stamp| stamp.checked_in_at }
        column("付与経路") { |stamp| stamp.source }
        column("付与した管理者") { |stamp| stamp.granted_by&.email }
      end
    end
  end

  form do |f|
    f.inputs do
      f.input :display_name, label: "表示名"

      if f.object.persisted?
        f.input :card_number, label: "カード番号"
        f.input :line_user_id, label: "LINE ID"
        f.input :avatar_url, label: "アバターURL"
      else
        para "カード番号は保存時にシステムが自動採番します。LINE連携は未設定のまま作成されます(紙カード来場者用)。"
      end
    end
    f.actions
  end

  controller do
    def create
      super do |success, _failure|
        success.html { redirect_to admin_visitor_path(resource), notice: "会員カードを発行しました(カード番号: #{resource.card_number})" }
      end
    end
  end

  member_action :grant_stamp, method: :post do
    visitor = resource
    event = Event.find(params[:event_id])
    stamp = visitor.stamps.new(
      event: event,
      checked_in_at: Time.current,
      source: :staff_manual,
      granted_by: current_admin_user,
    )

    if stamp.save
      redirect_to admin_visitor_path(visitor), notice: "「#{event.title}」のスタンプを付与しました"
    elsif stamp.errors.of_kind?(:visitor_id, :taken)
      redirect_to admin_visitor_path(visitor), alert: "既にこのイベントでチェックイン済みです"
    else
      redirect_to admin_visitor_path(visitor), alert: "付与できませんでした(#{stamp.errors.full_messages.join('、')})"
    end
  rescue ActiveRecord::RecordNotUnique
    redirect_to admin_visitor_path(visitor), alert: "既にこのイベントでチェックイン済みです"
  end
end
